import { Inter, Mono } from "next/font/google"; // Inter es una fuente válida, por ejemplo
import "./globals.css";

// Usa una fuente válida
const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const monoFont = Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${interFont.variable} ${monoFont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}


